### ISSUE TITLE
GitBook Video

### ISSUE THREAD

**Issue by FantasyJXF** [zhangjikai/communication#2]
GitBook上添加了local-video插件之后，按照你的配置 确实是可以在页面上添加视频了，但是遇到一个问题，就是视频很小，不是720p之类的，你说需要加一个
.video-js {
    width:100%;
    height: 100%;
}
这个需要在哪里配置呢

**Comment by zhangjikai** [comment]
你先下载GitBook Editor，然后找到下面的配置，点击之后会自动生成一个website.css，在这个css文件里添加样式 

![default](https://cloud.githubusercontent.com/assets/10095634/16354941/1d6e813c-3ada-11e6-879d-e992866bbb94.PNG)  

![2](https://cloud.githubusercontent.com/assets/10095634/16354942/203be1ac-3ada-11e6-890e-25ded22dc579.PNG)
