### ISSUE TITLE
number font  error

### ISSUE THREAD

**Issue by FantasyJXF** [zhangjikai/communication#3]
GitBook数字的格式感觉有点不对的说
![13](https://cloud.githubusercontent.com/assets/16235526/16482639/3c026390-3ee3-11e6-9de0-78e63293b23a.png)
![12](https://cloud.githubusercontent.com/assets/16235526/16482640/401dd6a8-3ee3-11e6-89ac-8837ddd757d1.png)
这个是咋回事啊
我的GitBook地址   https://fantasyjxf.gitbooks.io/px4-wiki/content/

**Comment by zhangjikai** [comment]
![default](https://cloud.githubusercontent.com/assets/10095634/16484792/ca6e2722-3eed-11e6-8c07-36411b699352.PNG)
在我这里看没问题

**Comment by FantasyJXF** [comment]
有点意思

**Comment by zhangjikai** [comment]
你可以设置一下标题的字体试试，在website.css加上下面的内容

``` css
h1, h2{
    font-family: "Microsoft YaHei";
}
```
